language: java
sudo: false # Use container based builds. They are faster and we do not need sudo.
dist: trusty
jdk:
  - openjdk8
  - oraclejdk8
#fails on because because java 9.0.1 is not compatible with gradle 4.0 currently used by travis
# https://github.com/travis-ci/travis-ci/issues/8975
# therefore disabled until travis fixes it.
# - oraclejdk9

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

  - wget https://github.com/freeplane/freeplane-events/archive/master.zip -O /tmp/freeplane-events.zip
  - unzip /tmp/freeplane-events.zip /tmp
  - bash -c "cd /tmp/freeplane-events &&  gradle clean publishToMavenLocal"

script:
  - gradle -PTestLoggingFull=true check
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
